version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code/
    # environment:
    #   - CELERY_BROKER=redis://redis:6379/0
    #   - CELERY_BACKEND=redis://redis:6379/0
    depends_on: 
      - db 
  db: 
    image: postgres:16
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=roozbehsarcheshme1381"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: roozbehsarcheshme1381
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  
  # celery:
  #   build: .
  #   command: celery worker --app=Blog --loglevel=info
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - app
  #     - redis

  # redis:
  #   image: "redis:alpine"

volumes:
  db:
    driver: local
  pgadmin:

