# Generated by Django 5.0.1 on 2024-02-07 18:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime_created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='datetime_updated')),
                ('status', models.CharField(choices=[('none', 'none'), ('size', 'size'), ('color', 'color'), ('both', 'both')], max_length=10, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
