# Generated by Django 5.0.1 on 2024-02-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
