# Generated by Django 5.0.1 on 2024-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_similar_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
