# Generated by Django 5.0.1 on 2024-02-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='discount')),
                ('inventory', models.IntegerField(verbose_name='inventory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='product.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.product', verbose_name='product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='product.size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
