# Generated by Django 5.0.1 on 2024-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_variant_color_alter_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='inventory'),
        ),
    ]
