# Generated by Django 5.0.1 on 2024-02-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_variant_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
    ]
