# Generated by Django 5.0.1 on 2024-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_is_parent_category_has_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='has_parent',
            field=models.BooleanField(default=False, verbose_name='has_parent'),
        ),
    ]
